name: Deploy to DigitalOcean

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: digitalocean
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Deploy to DigitalOcean
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        script: |
          cd /root/flipnosis-digitalocean
          git pull origin main
          cd digitalocean-deploy
          docker-compose down
          docker-compose build --no-cache
          docker-compose up -d
          docker-compose exec app node scripts/migrate-database-schema.js || true
          echo "Deployment completed successfully!"
